- name: Install Docker on Remote Machine
  hosts: all
  become: true  # Para ejecutar con sudo
  tasks:
    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker installation script
      command: sh /tmp/get-docker.sh
